# Generated by Django 5.2.13 on 2026-05-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên Dự Án/Tiệm Vàng')),
                ('file_path', models.FileField(upload_to='excels/%Y/%m/', verbose_name='File Excel Gốc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang bóc tách'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Lỗi hệ thống')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': '1. Dự án Excel',
                'verbose_name_plural': '1. Dự án Excel',
            },
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Sheet')),
                ('category', models.CharField(blank=True, help_text='VD: Thu mua, Cầm đồ...', max_length=100, null=True, verbose_name='Phân loại nghiệp vụ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='app_miner.excelproject', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': '2. Danh mục Sheet',
                'verbose_name_plural': '2. Danh mục Sheet',
            },
        ),
        migrations.CreateModel(
            name='ExcelTableRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Vùng')),
                ('coordinates', models.CharField(help_text='Ví dụ: A1:M20', max_length=50, verbose_name='Tọa độ (Range)')),
                ('region_type', models.CharField(default='FORM', help_text='FORM (nhập liệu) hoặc LIST (danh sách)', max_length=50, verbose_name='Loại vùng')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='app_miner.excelsheet', verbose_name='Sheet')),
            ],
            options={
                'verbose_name': '3. Vùng Nghiệp Vụ',
                'verbose_name_plural': '3. Vùng Nghiệp Vụ',
            },
        ),
        migrations.CreateModel(
            name='UncertaintyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi AI')),
                ('admin_answer', models.TextField(blank=True, null=True, verbose_name='Câu trả lời của anh Vũ')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Đã nạp tri thức')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_miner.excelproject', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': '5. Nhật ký AI tự học',
                'verbose_name_plural': '5. Nhật ký AI tự học',
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_address', models.CharField(max_length=10, verbose_name='Địa chỉ ô')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn AI/Nghiệp vụ')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Giá trị hiển thị')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='Công thức gốc')),
                ('color_code', models.CharField(default='FFFFFF', max_length=20, verbose_name='Mã màu ô')),
                ('is_required', models.BooleanField(default=False, verbose_name='Bắt buộc nhập')),
                ('metadata', models.JSONField(default=dict, help_text='Chứa logic phụ và liên kết xuyên sheet', verbose_name='Dữ liệu máy học')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app_miner.excelsheet', verbose_name='Sheet')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_miner.exceltableregion', verbose_name='Vùng dữ liệu')),
            ],
            options={
                'verbose_name': '4. Chi tiết Ô',
                'verbose_name_plural': '4. Chi tiết Ô',
                'unique_together': {('sheet', 'cell_address')},
            },
        ),
    ]
