# Generated by Django 5.2.13 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_miner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kiểu dữ liệu'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='parent_cells',
            field=models.ManyToManyField(blank=True, related_name='child_cells', to='app_miner.datafield'),
        ),
        migrations.AddField(
            model_name='excelsheet',
            name='confidence_score',
            field=models.FloatField(default=0.0, verbose_name='Độ tin cậy (Cosine)'),
        ),
        migrations.AddField(
            model_name='excelsheet',
            name='description',
            field=models.TextField(blank=True, help_text='AI sẽ tổng hợp các DataField để viết vào đây. Dùng câu này để tính Vector.', null=True, verbose_name='Mô tả nghiệp vụ AI soạn'),
        ),
        migrations.AddField(
            model_name='excelsheet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata Sheet'),
        ),
        migrations.AlterField(
            model_name='excelsheet',
            name='category',
            field=models.CharField(blank=True, help_text='Tên nghiệp vụ tạm thời (thường lấy theo tên Sheet)', max_length=100, null=True, verbose_name='Phân loại nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='excelsheet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Sheet gốc'),
        ),
    ]
