# Generated by Django 5.2.13 on 2026-05-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_miner', '0002_datafield_data_type_datafield_parent_cells_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='is_required',
        ),
        migrations.AddField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('LOGIC', 'Công thức/Tính toán'), ('UI', 'Giao diện (Nút/Nhãn rác)'), ('DATA', 'Dữ liệu nghiệp vụ'), ('TRASH', 'Dữ liệu thừa/Trống')], default='DATA', max_length=10, verbose_name='Phân loại Field'),
        ),
        migrations.AddField(
            model_name='excelsheet',
            name='refine_status',
            field=models.CharField(choices=[('PENDING', 'Chờ AI'), ('EXTRACTED', 'Đã vét thô'), ('REFINED', 'Đã tinh chế')], default='PENDING', max_length=20, verbose_name='Trạng thái tinh chế'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Công thức'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Dữ liệu máy học'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_miner.exceltableregion'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='excelsheet',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='excelsheet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả nghiệp vụ AI soạn'),
        ),
        migrations.AlterField(
            model_name='excelsheet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata Tổng Hợp (Đã phân loại)'),
        ),
        migrations.AlterField(
            model_name='exceltableregion',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Tọa độ (Range)'),
        ),
        migrations.AlterField(
            model_name='exceltableregion',
            name='region_type',
            field=models.CharField(default='FORM', max_length=50, verbose_name='Loại vùng'),
        ),
        migrations.AlterField(
            model_name='uncertaintylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_miner.excelproject'),
        ),
        migrations.AlterField(
            model_name='uncertaintylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
