# Generated by Django 5.2.13 on 2026-05-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_miner', '0003_remove_datafield_color_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UncertaintyLog',
        ),
    ]
