# Generated by Django 5.2.16 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Phiên bản')),
                ('description', models.TextField(verbose_name='Mô tả thay đổi')),
                ('content', models.TextField(verbose_name='Nội dung blueprint (Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bản đồ kiến trúc',
            },
        ),
    ]
