# Generated by Django 5.2.16 on 2026-07-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ví dụ: v1.0.0, v1.1.0-beta', max_length=50, unique=True, verbose_name='Phiên bản kiến trúc')),
                ('title', models.CharField(help_text='Tên mô tả ngắn gọn cho bản cập nhật kiến trúc này.', max_length=255, verbose_name='Tiêu đề bản thiết kế')),
                ('code_flow_mermaid', models.TextField(blank=True, help_text='Mã nguồn Mermaid minh họa luồng dữ liệu: User -> FileProcessor -> VectorStore -> LLM.', verbose_name='Sơ đồ luồng mã nguồn (Code Flow)')),
                ('erd_mermaid', models.TextField(blank=True, help_text='Mã nguồn ERD sinh tự động hoặc tùy chỉnh thủ công gắn liền với ranh giới group_id.', verbose_name='Sơ đồ thực thể ERD (Tự động quét từ Models)')),
                ('state_machine_mermaid', models.TextField(blank=True, help_text='Mô tả vòng đời tri thức KnowledgeUnit: pending -> approved/rolled_back.', verbose_name='Sơ đồ trạng thái (State Machine)')),
                ('component_mermaid', models.TextField(blank=True, help_text='Mô tả sự tương tác giữa các app cốt lõi trong hệ thống Modular Monolith.', verbose_name='Sơ đồ kiến trúc Module (Component Diagram)')),
                ('description', models.TextField(blank=True, help_text='Giải thích lý do (Why) đằng sau các quyết định kiến trúc trong phiên bản này.', verbose_name='Mô tả chi tiết thay đổi')),
                ('is_active', models.BooleanField(default=False, help_text='Đánh dấu phiên bản kiến trúc hiện hành đang chạy trên hệ thống.', verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name': 'Bản thiết kế hệ thống',
                'verbose_name_plural': 'Các bản thiết kế hệ thống',
                'ordering': ['-created_at'],
            },
        ),
    ]
