"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import codecs
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Thêm vào cuối file hoặc mục cấu hình AI
# VECTOR_DB_PATH = os.path.join(BASE_DIR, 'vector_db')
VECTOR_DB_PATH = os.path.join(BASE_DIR, 'core', 'vector_db')


# Lấy api_key các modles
load_dotenv()

GROQ_API_KEY = os.getenv('GROQ_API_KEY')
GEMINI_MODEL = os.getenv('GEMINI_MODEL')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL')



# Hố trợ tiếng việt file log: Đảm bảo standard output luôn dùng UTF-8 trên mọi môi trường Windows/Linux
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding.lower() != 'utf-8':
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x7mhglr1)cnokamnzo%35t%xw%!r2-hmm^f1xct&+@^o+^(h-o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Apps hệ thống Django
    'jazzmin',  # ĐẶT DÒNG NÀY TRƯỚC 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Thư viện app cài thêm
    'widget_tweaks', #pip install django-widget-tweaks khắc phục lỗi {{ field|add_class:"form-control" }} khi cấu hình giao diện kế thừa django admin
    'django.contrib.humanize', # Chuẩn hoá tiếng việt trên giao diện và template HTML, filter |intcomma (chưa thực hiện)
    

    # Apps thêm vào (Đúng chuẩn Namespace 'apps.xxx')
    'apps.core',
    'apps.group_chat',
    'apps.ai_assistant',
    'apps.subscriptions',
    'apps.arch_manager',  # Chỉ khai báo 1 lần duy nhất với đầy đủ namespace
    'channels',


   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 🌟 Thêm dòng này để Uvicorn serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Add from apps.core
    # 'apps.core.middleware.CompanyMiddleware', # Thêm dòng này vào sau AuthenticationMiddleware

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Các processor mặc định của Django...
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Bổ sung context processor của dự án VnxChatBot
                'apps.core.context_processors.user_groups_processor',
            ],
        },
    },
]




WSGI_APPLICATION = 'config.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'TEST': {
            'NAME': BASE_DIR / 'test_db.sqlite3', # Ép buộc Django dùng file vật lý thay vì in-memory khi chạy test
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'vi-vn'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Ho_Chi_Minh'

# Bật các tính năng liên quan đến định dạng số, ngày tháng, tiền tệ
USE_I18N = True
USE_L10N = True
USE_TZ = True
# Định dạng định dạng số và tiền tệ theo chuẩn Việt Nam
FORMAT_MODULE_PATH = 'config.formats'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_URL = '/static/'

# Thư mục chứa các file static chung của toàn dự án
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Thư mục lưu trữ khi chạy lệnh collectstatic (cho môi trường production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- AUTHENTICATION CONFIGURATION ---
AUTH_USER_MODEL = 'core.User'  # Khai báo Model gốc

# URL xử lý đăng nhập & chuyển hướng
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:dashboard' # Trang chủ sau khi đăng nhập
LOGOUT_REDIRECT_URL = 'core:login'    # Trang chủ sau khi đăng xuất


JAZZMIN_SETTINGS = {
    "site_title": "NexusChat Admin",
    "site_header": "NexusChat",
    "site_brand": "NexusChat",
    "welcome_sign": "Chào mừng đến với hệ thống quản trị",
    
    # Đồng bộ màu sắc với Sidebar #2c3e50 của bạn
    # "custom_css": "css/custom_admin.css",  # Bạn có thể tạo file này để tinh chỉnh thêm
    "custom_css": "css/ledger_theme.css",
    "theme": "flatly",  # Theme này có tone màu sáng, sạch sẽ và chuyên nghiệp
    
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Đồng bộ các menu
    "icons": {
        "auth": "fas fa-users-cog",
        "core.Company": "fas fa-building",
        "core.Profile": "fas fa-user",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_fixed": True,           # Cố định Navbar trên đầu
    "sidebar_fixed": True,          # Cố định Sidebar
    "layout_boxed": False,          # QUAN TRỌNG: Phải là False
    "sidebar": "sidebar-dark-primary",
}


# Thêm cấu hình kết nối tới Redis (chạy mặc định trên port 6379):
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


# Cấu hình Celery Broker trỏ tới Redis với timeout hợp lý
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Hiển thị log radeis:
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# --- CHANNELS & WEBSOCKET CONFIGURATION: Xử lý bất đồng bộ tin nhắn ---
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#             "capacity": 1500,         # Tăng dung lượng hàng đợi tin nhắn
#             "expiry": 60,             # Thời gian hết hạn message (giây)
#             "symmetric_encryption_keys": [SECRET_KEY],
#         },
#     },
# }

# # Khi đưa lên server: Đọc cấu hình Redis từ biến môi trường, mặc định trỏ về localhost nếu chạy local
# REDIS_HOST = os.environ.get("REDIS_HOST", "127.0.0.1")
# REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(REDIS_HOST, int(REDIS_PORT))],
#             "capacity": 1500,
#             "expiry": 60,
#         },
#     },
# }

# Dùng tạm khi debug local nếu không muốn phụ thuộc Redis service
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
# Cấu hình định tuyến ASGI cho Django Channels & WebSocket
ASGI_APPLICATION = 'config.asgi.application'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug_vnx.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8', # 🛠️ Đảm bảo hỗ trợ tiếng Việt không bị lỗi font
        },
        # Giữ lại console handler nhưng cấu hình level cao hơn (ví dụ: WARNING hoặc chỉ dùng cho trường hợp ngoại lệ)
        'console': {
            'level': 'WARNING', 
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'apps': {
            'handlers': ['file'],  # 🛠️ Chỉ giữ lại 'file', loại bỏ 'console' để dọn sạch terminal
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}