# Generated by Django 5.2.13 on 2026-05-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Thuật ngữ/Logic')),
                ('category', models.CharField(choices=[('LOGIC', 'Logic'), ('TERM', 'Từ điển')], max_length=50)),
                ('content', models.TextField(verbose_name='Mô tả chi tiết cho AI')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('origin_metadata', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_miner.excelproject')),
            ],
            options={
                'verbose_name': 'Bản thảo tri thức',
                'verbose_name_plural': 'Bản thảo tri thức',
            },
        ),
    ]
