# Generated by Django 5.2.13 on 2026-05-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coach', '0002_datatype_system_prompt_datatype_user_prompt_template'),
        ('app_knowledge', '0001_initial'),
        ('app_miner', '0002_datafield_data_type_datafield_parent_cells_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedraft',
            name='backup_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_coach.datatype'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_draft', to='app_miner.excelsheet'),
        ),
    ]
