# Generated by Django 5.2.13 on 2026-05-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_knowledge', '0002_knowledgedraft_backup_hash_knowledgedraft_data_type_and_more'),
        ('app_miner', '0003_remove_datafield_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedraft',
            name='category',
            field=models.CharField(choices=[('LOGIC', 'Logic tính toán'), ('TERM', 'Định nghĩa/Nghiệp vụ')], default='TERM', max_length=50, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='content',
            field=models.TextField(help_text='Đây là nơi anh Vũ tinh chỉnh nội dung sau khi AI tóm tắt thô.', verbose_name='Mô tả chi tiết cho AI'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='origin_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata gốc từ Miner'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='app_miner.excelproject'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ AI tóm tắt'), ('AI_READY', 'AI đã soạn xong'), ('EDITED', 'Anh Vũ đã sửa'), ('FINAL', 'Đã chốt (Nạp vào RAG)')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
