# Generated by Django 5.2.13 on 2026-05-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_knowledge', '0003_alter_knowledgedraft_category_and_more'),
        ('app_miner', '0004_delete_uncertaintylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedraft',
            options={'verbose_name': '1. Bản thảo tri thức', 'verbose_name_plural': '1. Bản thảo tri thức'},
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='content',
            field=models.TextField(verbose_name='Mô tả chi tiết cho AI'),
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi AI')),
                ('admin_answer', models.TextField(blank=True, null=True, verbose_name='Câu trả lời của anh Vũ')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Đã nạp tri thức')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_miner.excelproject', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': '2. Nhật ký AI tự học',
                'verbose_name_plural': '2. Nhật ký AI tự học',
            },
        ),
    ]
