# Generated by Django 5.2.13 on 2026-05-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã định danh')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI tự tạo')),
                ('confidence_score', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Loại tri thức',
                'verbose_name_plural': '1. Danh mục loại tri thức',
            },
        ),
        migrations.CreateModel(
            name='IntentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_code', models.CharField(max_length=100, unique=True, verbose_name='Mã ý định')),
                ('display_name', models.CharField(max_length=255, verbose_name='Tên nghiệp vụ')),
                ('keywords', models.TextField(help_text='Cách nhau bởi dấu phẩy', verbose_name='Từ khóa nhận diện')),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('knowledge_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype', verbose_name='Loại tri thức (Nghiệp vụ)')),
            ],
            options={
                'verbose_name': 'Điều hướng & Ý định',
                'verbose_name_plural': '3. Trung tâm điều hướng Intent',
            },
        ),
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Câu hỏi khách')),
                ('ai_response_logic', models.JSONField(verbose_name='Các bước AI thực hiện')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Đúng/Sai')),
                ('feedback_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú chỉnh sửa (VD: Phải bù 60k cho khách)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='system_monitor.intentmanagement')),
            ],
            options={
                'verbose_name': 'Nhật ký huấn luyện',
                'verbose_name_plural': '4. Nhật ký & Huấn luyện (RLHF)',
            },
        ),
        migrations.CreateModel(
            name='ProjectStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('obj_type', models.CharField(choices=[('FILE', 'File'), ('CLASS', 'Class'), ('FUNC', 'Function')], max_length=10)),
                ('docstring', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='AI tóm tắt')),
                ('level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_monitor.projectstructure')),
            ],
            options={
                'verbose_name': 'Cấu trúc mã nguồn',
                'verbose_name_plural': '2. Bản đồ cấu trúc Code',
            },
        ),
        migrations.AddField(
            model_name='intentmanagement',
            name='handler_func',
            field=models.ForeignKey(blank=True, limit_choices_to={'obj_type': 'FUNC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.projectstructure', verbose_name='Hàm xử lý (Code)'),
        ),
    ]
