# Generated by Django 5.2.13 on 2026-04-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã định danh')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả loại tri thức')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Do AI tự tạo')),
                ('confidence_score', models.FloatField(default=1.0, verbose_name='Độ tin cậy của AI')),
            ],
            options={
                'verbose_name': 'Loại tri thức',
                'verbose_name_plural': 'Các loại tri thức (Dynamic)',
            },
        ),
        migrations.CreateModel(
            name='IntentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='Câu hỏi người dùng')),
                ('detected_intent', models.CharField(max_length=255, verbose_name='Ý định đoán được')),
                ('response_logic', models.JSONField(verbose_name='Logic phản hồi')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Đánh giá từ anh Vũ')),
                ('feedback_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú chỉnh sửa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ý định người dùng',
                'verbose_name_plural': 'Huấn luyện Router (AI Learning)',
            },
        ),
        migrations.CreateModel(
            name='ProjectStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='Đường dẫn định danh')),
                ('name', models.CharField(max_length=255, verbose_name='Tên đối tượng')),
                ('obj_type', models.CharField(choices=[('FILE', 'File'), ('CLASS', 'Class'), ('FUNC', 'Function')], max_length=10, verbose_name='Phân loại')),
                ('docstring', models.TextField(blank=True, null=True, verbose_name='Ghi chú trong code')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='AI tóm tắt chức năng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn tồn tại')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu trúc mã nguồn',
                'verbose_name_plural': 'Bản đồ cấu trúc hệ thống',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50, verbose_name='Hành động (Import/Export)')),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Báo cáo kết quả')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype', verbose_name='Loại dữ liệu')),
            ],
            options={
                'verbose_name': 'Lịch sử trao đổi',
                'verbose_name_plural': 'Lịch sử Import/Export Tri thức',
            },
        ),
    ]
