# Generated by Django 5.2.13 on 2026-04-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstructure',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstructure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_monitor.projectstructure', verbose_name='Cấp cha'),
        ),
    ]
