# Generated by Django 5.2.13 on 2026-04-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0002_projectstructure_level_projectstructure_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=100, unique=True, verbose_name='Mã ý định (Ví dụ: TRAO_DOI_VANG)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('target_function', models.ForeignKey(blank=True, limit_choices_to={'obj_type': 'FUNC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.projectstructure', verbose_name='Hàm xử lý logic')),
            ],
            options={
                'verbose_name': 'Cấu hình điều hướng',
                'verbose_name_plural': 'Bảng điều hướng Intent (Router Mapping)',
            },
        ),
    ]
