# Generated by Django 5.2.13 on 2026-04-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0003_intentmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntentMapping',
        ),
    ]
