# Generated by Django 5.2.13 on 2026-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideentry',
            name='ai_notes',
            field=models.TextField(blank=True, help_text='Yêu cầu riêng cho bài này, AI không được bỏ qua.', verbose_name='Ghi chú bắt buộc cho AI'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='ai_prompt_template',
            field=models.TextField(blank=True, help_text='Cấu trúc lệnh để AI dựa vào soạn bài.', verbose_name='Prompt mẫu (System)'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='code_example',
            field=models.TextField(blank=True, verbose_name='Mã code ví dụ (Cypher/Python)'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='image_example',
            field=models.ImageField(blank=True, null=True, upload_to='guides/images/', verbose_name='Hình ảnh minh họa'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Chỉ những bài đã duyệt mới hiển thị cho người dùng.', verbose_name='Đã duyệt nội dung'),
        ),
        migrations.AlterField(
            model_name='guideentry',
            name='order',
            field=models.FloatField(default=0.0, verbose_name='Thứ tự chèn'),
        ),
        migrations.AlterField(
            model_name='guideentry',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Kiến thức cần có'),
        ),
    ]
