# Generated by Django 5.2.13 on 2026-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_guide', '0002_guideentry_ai_notes_guideentry_ai_prompt_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideentry',
            name='is_system_generated',
            field=models.BooleanField(default=False, verbose_name='Bài viết hệ thống tự động'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='system_app_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='App liên quan'),
        ),
    ]
