# Generated by Django 5.2.13 on 2026-05-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên Nguồn Dữ Liệu/Dự Án')),
                ('file_path', models.FileField(upload_to='knowledge_sources/%Y/%m/', verbose_name='Tệp tin gốc')),
                ('file_type', models.CharField(choices=[('EXCEL', 'File Excel nghiệp vụ'), ('DOCX', 'Tài liệu Word (Quy định/Hợp đồng)'), ('TXT', 'File Text thô'), ('CSV', 'Bảng dữ liệu phẳng (CSV)'), ('IMAGE', 'Ảnh chụp (Toa hàng/Biên lai)')], default='EXCEL', max_length=10, verbose_name='Định dạng tệp')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang bóc tách'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Lỗi hệ thống')], default='PENDING', max_length=20, verbose_name='Trạng thái xử lý')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': '1. Nguồn Tri Thức Thô',
                'verbose_name_plural': '1. Nguồn Tri Thức Thô',
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Phân Mục/Sheet gốc')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại nghiệp vụ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả tóm tắt (AI soạn)')),
                ('processed_content', models.TextField(blank=True, null=True, verbose_name='Nội dung chữ thô bóc tách (Dùng cho RAG)')),
                ('content_json', models.JSONField(blank=True, default=dict, verbose_name='Cấu trúc dữ liệu phẳng (JSON)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Tổng Hợp Excel (Đã phân loại)')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Độ tin cậy trích xuất')),
                ('refine_status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('EXTRACTED', 'Đã vét thô'), ('REFINED', 'Đã tinh chế')], default='PENDING', max_length=20, verbose_name='Trạng thái tinh chế')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app_miner.datasource', verbose_name='Nguồn dữ liệu')),
            ],
            options={
                'verbose_name': '2. Phân Mục Tri Thức',
                'verbose_name_plural': '2. Phân Mục Tri Thức',
            },
        ),
        migrations.CreateModel(
            name='ExcelTableRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Vùng')),
                ('coordinates', models.CharField(max_length=50, verbose_name='Tọa độ (Range)')),
                ('region_type', models.CharField(default='FORM', max_length=50, verbose_name='Loại vùng')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='app_miner.dataentry', verbose_name='Mục tri thức')),
            ],
            options={
                'verbose_name': '3. Vùng Nghiệp Vụ (Excel)',
                'verbose_name_plural': '3. Vùng Nghiệp Vụ (Excel)',
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('LOGIC', 'Công thức/Tính toán'), ('UI', 'Giao diện (Nút/Nhãn rác)'), ('DATA', 'Dữ liệu nghiệp vụ'), ('TRASH', 'Dữ liệu thừa/Trống')], default='DATA', max_length=10, verbose_name='Phân loại Field')),
                ('cell_address', models.CharField(max_length=10, verbose_name='Địa chỉ ô')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn nghiệp vụ')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Giá trị')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='Công thức')),
                ('metadata', models.JSONField(default=dict, verbose_name='Dữ liệu máy học')),
                ('parent_cells', models.ManyToManyField(blank=True, related_name='child_cells', to='app_miner.datafield')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app_miner.dataentry', verbose_name='Mục tri thức')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_miner.exceltableregion')),
            ],
            options={
                'verbose_name': '4. Chi tiết Ô (Excel)',
                'verbose_name_plural': '4. Chi tiết Ô (Excel)',
                'unique_together': {('sheet', 'cell_address')},
            },
        ),
    ]
