# Generated by Django 5.2.16 on 2026-07-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Các tin nhắn'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_processed_by_ai',
            field=models.BooleanField(default=False, help_text='Đánh dấu tin nhắn đã được AI phân tích'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Người dùng'), ('ai', 'AI Assistant')], default='user', max_length=10, verbose_name='Loại người gửi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_chat.chatgroup', verbose_name='Nhóm chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
    ]
