# Generated by Django 5.2.13 on 2026-05-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại dữ liệu')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã (Miner code)')),
                ('is_important', models.BooleanField(default=False, verbose_name='Trọng tâm nghiệp vụ')),
            ],
            options={
                'verbose_name': '1. Loại dữ liệu cấu hình',
                'verbose_name_plural': '1. Loại dữ liệu cấu hình',
            },
        ),
    ]
