# Generated by Django 5.2.13 on 2026-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Dạy AI đóng vai gì (VD: Chuyên gia tiệm vàng)', null=True, verbose_name='System Prompt cho AI'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='user_prompt_template',
            field=models.TextField(blank=True, help_text='Dùng {{metadata}} để truyền dữ liệu vào', null=True, verbose_name='User Prompt Template'),
        ),
    ]
