# Generated by Django 5.2.13 on 2026-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coach', '0002_datatype_system_prompt_datatype_user_prompt_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Cấu hình AI Coach', 'verbose_name_plural': 'Cấu hình AI Coach'},
        ),
        migrations.AddField(
            model_name='datatype',
            name='ai_model_preference',
            field=models.CharField(choices=[('GROQ', 'Groq (Nhanh/Nghiệp vụ thường)'), ('OLLAMA', 'Ollama (Bảo mật/Logic phức tạp)')], default='GROQ', max_length=50, verbose_name='Ưu tiên Model'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Dạy AI đóng vai gì. VD: Bạn là kế toán trưởng tiệm vàng Ứng Dụng Vàng chuyên về định giá.', null=True, verbose_name='System Prompt cho AI'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='user_prompt_template',
            field=models.TextField(blank=True, help_text='Dùng biến {{metadata}} để AI biết chỗ dán dữ liệu Excel vào và {{sheet_name}} để lấy tên sheet.', null=True, verbose_name='User Prompt Template'),
        ),
    ]
