# Generated by Django 5.2.16 on 2026-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tính năng')),
                ('slug', models.SlugField(unique=True, verbose_name='Mã định danh')),
            ],
            options={
                'verbose_name': 'Tính năng (App)',
                'verbose_name_plural': 'Các tính năng',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('features', models.ManyToManyField(to='subscriptions.feature', verbose_name='Các tính năng được cấp')),
            ],
            options={
                'verbose_name': 'Gói dịch vụ',
                'verbose_name_plural': 'Các gói dịch vụ',
            },
        ),
    ]
