# Generated by Django 5.2.16 on 2026-07-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tính năng')),
                ('slug', models.SlugField(unique=True, verbose_name='Mã định danh (Slug)')),
            ],
            options={
                'verbose_name': 'Tính năng',
                'verbose_name_plural': 'Các tính năng',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('slug', models.SlugField(unique=True, verbose_name='Mã gói (Slug)')),
                ('price', models.DecimalField(decimal_places=0, help_text='Số tiền khách hàng phải trả hàng tháng.', max_digits=12, verbose_name='Giá tiền (VNĐ/tháng)')),
                ('description', models.TextField(help_text='Mô tả ngắn gọn về gói dịch vụ.', verbose_name='Mô tả chi tiết')),
                ('features', models.ManyToManyField(to='subscriptions.feature', verbose_name='Tính năng bao gồm')),
            ],
            options={
                'verbose_name': 'Gói dịch vụ',
                'verbose_name_plural': 'Các gói dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company', verbose_name='Công ty')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='Gói dịch vụ hiện tại')),
            ],
            options={
                'verbose_name': 'Đăng ký dịch vụ công ty',
                'verbose_name_plural': 'Đăng ký dịch vụ công ty',
            },
        ),
    ]
