# Generated by Django 5.2.16 on 2026-07-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Loại gói dịch vụ')),
                ('member_limit', models.IntegerField(default=6, help_text='Tổng số thành viên tối đa (bao gồm AI)', verbose_name='Giới hạn thành viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
            ],
            options={
                'verbose_name': 'Đăng ký dịch vụ nhóm',
                'verbose_name_plural': 'Đăng ký dịch vụ nhóm',
            },
        ),
    ]
