# Generated by Django 6.0.7 on 2026-07-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Công ty', 'verbose_name_plural': 'Công ty'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
    ]
