# Generated by Django 5.2.16 on 2026-07-09 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Số chứng từ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('date', models.DateField(verbose_name='Ngày chứng từ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Diễn giải')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Công ty sở hữu')),
            ],
            options={
                'verbose_name': 'Chứng từ',
                'verbose_name_plural': 'Các chứng từ',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
