# Generated by Django 5.2.16 on 2026-08-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('ollama', 'Ollama'), ('openai', 'OpenAI GPT')], default='gemini', help_text='Nhà cung cấp LLM mặc định là Google Gemini.', max_length=20, verbose_name='Nhà cung cấp')),
                ('api_key', models.CharField(blank=True, help_text='Khóa bí mật do người dùng cung cấp riêng cho nhóm.', max_length=255, null=True, verbose_name='API Key')),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='Tên phiên bản model cụ thể (VD: qwen2.5:7b cho Ollama).', max_length=100, verbose_name='Tên Model')),
            ],
            options={
                'verbose_name': 'Cấu hình AI nhóm',
                'verbose_name_plural': 'Cấu hình AI nhóm',
            },
        ),
    ]
