# Generated by Django 5.2.16 on 2026-07-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaiprovider',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='group_chat.chatgroup', verbose_name='Nhóm chat'),
        ),
    ]
