# Generated by Django 5.2.16 on 2026-07-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_initial'),
        ('group_chat', '0003_document_processed_at_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaiprovider',
            name='api_key',
            field=models.CharField(blank=True, help_text='Khóa bí mật do người dùng cung cấp riêng cho nhóm (bỏ trống nếu dùng chung hệ thống).', max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='groupaiprovider',
            name='group',
            field=models.OneToOneField(help_text='Nhóm làm việc sở hữu cấu hình AI riêng biệt này.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='group_chat.chatgroup', verbose_name='Nhóm chat'),
        ),
        migrations.AlterField(
            model_name='groupaiprovider',
            name='model_name',
            field=models.CharField(default='gemini-1.5-pro', help_text='Tên phiên bản model cụ thể (mặc định cho Gemini).', max_length=100, verbose_name='Tên Model'),
        ),
        migrations.AlterField(
            model_name='groupaiprovider',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('ollama', 'Ollama'), ('openai', 'OpenAI GPT')], default='gemini', help_text='Nhà cung cấp LLM mặc định là Google Gemini.', max_length=20, verbose_name='Nhà cung cấp'),
        ),
    ]
