# Generated by Django 5.2.16 on 2026-08-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_groupaiprovider_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaiprovider',
            name='api_key',
            field=models.CharField(blank=True, help_text='Khóa bí mật do người dùng cung cấp riêng cho nhóm.', max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='groupaiprovider',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', help_text='Tên phiên bản model cụ thể (VD: qwen2.5:7b cho Ollama).', max_length=100, verbose_name='Tên Model'),
        ),
    ]
