# Generated by Django 5.2.16 on 2026-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('gemini', 'Google Gemini'), ('ollama', 'Ollama')], default='groq', max_length=20)),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('model_name', models.CharField(max_length=100, verbose_name='Tên Model (ví dụ: llama-3.3-70b)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Sử dụng mặc định')),
            ],
            options={
                'verbose_name': 'Cấu hình AI',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ai_knowledge_base/%Y/%m/%d/', verbose_name='Tệp tài liệu')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tài liệu nhóm',
            },
        ),
    ]
