# Generated by Django 5.2.13 on 2026-05-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Chủ đề lớn')),
                ('icon', models.CharField(default='fa-book', max_length=50, verbose_name='Icon (FontAwesome)')),
                ('order', models.FloatField(default=0.0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': '1. Nhóm Hướng dẫn',
                'verbose_name_plural': '1. Nhóm Hướng dẫn',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuideEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài học')),
                ('prerequisites', models.TextField(blank=True, help_text='Cần nhớ gì trước khi đọc?', verbose_name='Kiến thức cần có')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết (HTML/Markdown)')),
                ('future_notes', models.TextField(blank=True, verbose_name='Mở rộng sau này')),
                ('order', models.FloatField(default=0.0, help_text='Dùng 1.1, 1.2 để chèn vào giữa', verbose_name='Thứ tự chèn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chatbot_guide.guidecategory')),
            ],
            options={
                'verbose_name': '2. Bài viết chi tiết',
                'verbose_name_plural': '2. Bài viết chi tiết',
                'ordering': ['order'],
            },
        ),
    ]
