# Generated by Django 5.2.16 on 2026-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard Kiến trúc',
                'verbose_name_plural': 'NexusChat Dev',
                'managed': False,
            },
        ),
    ]
