# Generated by Django 5.2.13 on 2026-04-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('file_path', models.FileField(upload_to='excels/', verbose_name='File gốc')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dự án Excel',
                'verbose_name_plural': 'Dự án Excel',
            },
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Sheet')),
                ('sheet_index', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='excel_miner.excelproject')),
            ],
            options={
                'verbose_name': 'Sheet Excel',
                'verbose_name_plural': 'Danh sách Sheets',
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_address', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Ghi chú/Quy tắc trong ô')),
                ('confidence_score', models.FloatField(default=1.0, verbose_name='Độ tin cậy của AI')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Anh Vũ đã xác nhận')),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('field_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype', verbose_name='Loại dữ liệu (AI định nghĩa)')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='excel_miner.excelsheet')),
            ],
            options={
                'verbose_name': 'Trường dữ liệu',
                'verbose_name_plural': 'Dữ liệu chi tiết từ Sheets',
                'unique_together': {('sheet', 'cell_address')},
            },
        ),
    ]
