# Generated by Django 5.2.13 on 2026-05-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên dự án')),
                ('file_path', models.FileField(help_text='Hệ thống hỗ trợ .xlsx, .xls, .xlsm', upload_to='excels/%Y/%m/', verbose_name='File gốc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả dự án')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang bóc tách'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Lỗi')], default='PENDING', max_length=20, verbose_name='Trạng thái xử lý')),
            ],
            options={
                'verbose_name': 'Dự án Excel',
                'verbose_name_plural': 'Dự án Excel',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Sheet')),
                ('sheet_index', models.IntegerField()),
                ('category', models.CharField(blank=True, help_text='VD: GOLD_PRICE, EXCHANGE_LOGIC, INVENTORY', max_length=100, null=True, verbose_name='Loại nghiệp vụ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='excel_miner.excelproject')),
            ],
            options={
                'verbose_name': 'Sheet Excel',
                'verbose_name_plural': 'Danh sách Sheets',
                'unique_together': {('project', 'sheet_index')},
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_address', models.CharField(db_index=True, max_length=10)),
                ('label', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mã định danh')),
                ('smart_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn AI')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Giá trị hiển thị')),
                ('raw_value', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu thô')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='Công thức (Excel)')),
                ('logic_interpretation', models.TextField(blank=True, null=True, verbose_name='Giải thích logic ô')),
                ('functional_group', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nhóm nghiệp vụ')),
                ('ui_type', models.CharField(choices=[('INPUT', 'Ô nhập liệu'), ('OUTPUT', 'Ô kết quả/Tổng'), ('HEADER', 'Tiêu đề'), ('BUTTON', 'Nút bấm giả lập')], default='DATA_CELL', max_length=50, verbose_name='Loại thành phần')),
                ('is_required', models.BooleanField(default=False, verbose_name='Bắt buộc')),
                ('color_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã màu ô')),
                ('confidence_score', models.FloatField(default=1.0, verbose_name='Độ tin cậy AI (%)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Thông tin kỹ thuật khác')),
                ('field_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='excel_miner.excelsheet')),
            ],
            options={
                'verbose_name': 'Dữ liệu ô',
                'verbose_name_plural': 'Dữ liệu ô',
                'indexes': [models.Index(fields=['sheet', 'label'], name='excel_miner_sheet_i_8f0006_idx'), models.Index(fields=['functional_group', 'is_verified'], name='excel_miner_functio_9387d3_idx')],
                'unique_together': {('sheet', 'cell_address')},
            },
        ),
    ]
