# Generated by Django 5.2.13 on 2026-04-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_miner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Phân tích chuyên sâu (AI)'),
        ),
    ]
