# Generated by Django 5.2.13 on 2026-04-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_miner', '0002_datafield_metadata'),
        ('system_monitor', '0003_intentmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='raw_value',
            field=models.JSONField(blank=True, null=True, verbose_name='Giá trị gốc (Số/Ngày)'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú trong ô'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype', verbose_name='Loại dữ liệu'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vũ đã xác nhận'),
        ),
    ]
