# Generated by Django 5.2.13 on 2026-04-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_miner', '0003_datafield_raw_value_alter_datafield_comment_and_more'),
        ('system_monitor', '0004_delete_intentmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafield',
            options={'verbose_name': 'Dữ liệu trong Sheets', 'verbose_name_plural': 'Dữ liệu trong Sheets'},
        ),
        migrations.AlterField(
            model_name='datafield',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_monitor.datatype'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='raw_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
