# Generated by Django 5.2.13 on 2026-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_miner', '0004_alter_datafield_options_alter_datafield_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='functional_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datafield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafield',
            name='smart_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn AI'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='ui_type',
            field=models.CharField(default='DATA_CELL', max_length=50),
        ),
    ]
