# Generated by Django 5.2.16 on 2026-07-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('plan_type', models.CharField(default='free', help_text='Xác định giới hạn tính năng của nhóm', max_length=50, verbose_name='Gói dịch vụ')),
                ('max_members', models.IntegerField(default=6, verbose_name='Số thành viên tối đa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Nhóm đang hoạt động')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả nhóm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Nhóm chat',
                'verbose_name_plural': 'Các nhóm chat',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/groups/%Y/%m/%d/', verbose_name='Tệp tài liệu')),
                ('upload_type', models.CharField(choices=[('chat', 'Thảo luận'), ('auto', 'Tự động học')], max_length=10, verbose_name='Loại tải lên')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='VD: Vàng 610', max_length=100, verbose_name='Tên thực thể')),
                ('context_tag', models.CharField(help_text='VD: Giao dịch hoặc Tiêu chuẩn', max_length=100, verbose_name='Ngữ cảnh')),
                ('source_reference', models.CharField(max_length=255, verbose_name='Nguồn tham chiếu')),
                ('content', models.TextField(verbose_name='Nội dung kiến thức')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rollback', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái duyệt')),
                ('version', models.IntegerField(default=1, verbose_name='Phiên bản')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='group_chat.document', verbose_name='Tài liệu gốc')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='group_chat.chatgroup', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Đơn vị kiến thức',
                'verbose_name_plural': 'Đơn vị kiến thức',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20, verbose_name='Vai trò')),
                ('is_ai', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là thành viên AI của nhóm', verbose_name='Là AI?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thành viên nhóm',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
