# Generated by Django 5.2.16 on 2026-08-15 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('plan_type', models.CharField(default='free', max_length=50, verbose_name='Gói dịch vụ')),
                ('max_members', models.IntegerField(default=6, verbose_name='Số thành viên tối đa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Nhóm đang hoạt động')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả nhóm')),
                ('is_admin_group', models.BooleanField(default=False, verbose_name='Là nhóm Admin hệ thống?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Nhóm chat',
                'verbose_name_plural': 'Danh sách nhóm chat',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/groups/%Y/%m/%d/', verbose_name='Tệp tài liệu')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tệp gốc')),
                ('upload_type', models.CharField(choices=[('chat', 'Thảo luận'), ('auto', 'Tự động học')], default='chat', max_length=10, verbose_name='Loại tải lên')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý AI')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('can_approve_internal', models.BooleanField(default=False)),
                ('can_approve_public', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_chat.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20, verbose_name='Vai trò')),
                ('is_ai', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là thành viên AI', verbose_name='Là AI?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thành viên nhóm',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Đã học tổng hợp tri thức')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='group_chat.document', verbose_name='Tài liệu đính kèm')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='group_chat.message', verbose_name='Trả lời cho tin nhắn')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_chat.membership', verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Thích'), ('dislike', 'Không thích')], max_length=10, verbose_name='Loại phản hồi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Góp ý chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phản hồi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='group_chat.message', verbose_name='Tin nhắn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phản hồi')),
            ],
            options={
                'verbose_name': 'Phản hồi AI',
                'verbose_name_plural': 'Phản hồi AI',
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_type', models.CharField(help_text='pdf, xlsx, docx, etc.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('STAGING', 'Đang phân tích cấu trúc'), ('APPROVED', 'Đã duyệt & Sync'), ('FAILED', 'Lỗi/Dữ liệu rác')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Lưu thông tin layout, số trang, hash file.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
            ],
            options={
                'verbose_name': 'Tài liệu thô',
                'verbose_name_plural': 'Tài liệu thô',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_structure', models.JSONField(help_text='Cấu trúc tri thức dạng JSON.')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Điểm tin cậy từ Audit Agent')),
                ('tags', models.JSONField(default=list, help_text='Nhãn nghiệp vụ tự động gán.')),
                ('is_active', models.BooleanField(default=False, help_text='Chỉ True khi dữ liệu đã được Approved.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
                ('source_doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_node', to='group_chat.rawdocument')),
            ],
            options={
                'verbose_name': 'Cây tri thức',
                'verbose_name_plural': 'Cây tri thức',
            },
        ),
        migrations.CreateModel(
            name='BusinessGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='VD: 610, Vàng cha', max_length=100, verbose_name='Thuật ngữ gốc')),
                ('context_tag', models.CharField(help_text='VD: GOLD_NEW, GOLD_RAW', max_length=100, verbose_name='Nhãn ngữ cảnh')),
                ('synonyms', models.JSONField(default=list, help_text="['vàng 6 hội 1', 'hội 610']", verbose_name='Danh sách từ đồng nghĩa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả ý nghĩa nghiệp vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='group_chat.chatgroup', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Từ điển nghiệp vụ',
                'verbose_name_plural': 'Từ điển nghiệp vụ',
                'indexes': [models.Index(fields=['group', 'term', 'context_tag'], name='group_chat__group_i_ed8e0c_idx')],
                'unique_together': {('group', 'term', 'context_tag')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('has_conflict', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group_chat.knowledgechapter')),
            ],
            options={
                'verbose_name': 'Mục lục tri thức',
                'verbose_name_plural': 'Mục lục tri thức',
                'indexes': [models.Index(fields=['group_id', 'status'], name='group_chat__group_i_4b8fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='VD: Vàng 610', max_length=100, verbose_name='Tên thực thể')),
                ('context_tag', models.CharField(help_text='VD: GOLD_NEW, GOLD_RAW', max_length=100, verbose_name='Ngữ cảnh')),
                ('source_reference', models.CharField(max_length=255, verbose_name='Nguồn tham chiếu')),
                ('content', models.TextField(verbose_name='Nội dung kiến thức')),
                ('raw_structure_json', models.JSONField(blank=True, null=True, verbose_name='Cây mục lục gợi ý')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Điểm tin cậy (0.0-1.0)')),
                ('is_conflict', models.BooleanField(default=False, verbose_name='Phát hiện mâu thuẫn')),
                ('conflict_report', models.JSONField(blank=True, null=True, verbose_name='Chi tiết mâu thuẫn')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('staging', 'Đang phân tích/Xử lý mâu thuẫn'), ('approved', 'Đã duyệt'), ('rollback', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái duyệt')),
                ('version', models.IntegerField(default=1, verbose_name='Phiên bản')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='group_chat.document', verbose_name='Tài liệu gốc')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='group_chat.chatgroup', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Đơn vị kiến thức',
                'verbose_name_plural': 'Đơn vị kiến thức',
                'indexes': [models.Index(fields=['group', 'status', 'context_tag'], name='group_chat__group_i_681fec_idx'), models.Index(fields=['entity_name'], name='group_chat__entity__bc92de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['group', 'status'], name='group_chat__group_i_2766fd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetree',
            index=models.Index(fields=['group', 'is_active'], name='group_chat__group_i_2b1e0b_idx'),
        ),
    ]
