# Generated by Django 5.2.16 on 2026-07-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeunit',
            name='context_tag',
            field=models.CharField(help_text='VD: Giao dịch', max_length=100, verbose_name='Ngữ cảnh'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_ai',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu đây là thành viên AI', verbose_name='Là AI?'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_chat.membership', verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Thích'), ('dislike', 'Không thích')], max_length=10, verbose_name='Loại phản hồi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Góp ý chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phản hồi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='group_chat.chatgroup', verbose_name='Nhóm')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='group_chat.message', verbose_name='Tin nhắn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phản hồi')),
            ],
            options={
                'verbose_name': 'Phản hồi AI',
                'verbose_name_plural': 'Phản hồi AI',
            },
        ),
    ]
