# Generated by Django 5.2.16 on 2026-08-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictResolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField(verbose_name='Nội dung gốc hiện tại')),
                ('conflicting_content', models.TextField(verbose_name='Nội dung mới gây xung đột')),
                ('proposed_content', models.TextField(blank=True, null=True, verbose_name='Nội dung đề xuất (AI Rewrite / User Edit)')),
                ('conflict_reason', models.TextField(verbose_name='Lý do mâu thuẫn từ System Auditor')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang sửa đổi (AI Rewrite)'), ('resolved', 'Đã hợp nhất / Ghi đè'), ('discarded', 'Đã hủy / Giữ cũ')], default='pending', max_length=20, verbose_name='Trạng thái xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm phát sinh')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm giải quyết')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_logs', to='group_chat.chatgroup', verbose_name='Nhóm chat')),
                ('knowledge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_logs', to='group_chat.knowledgeunit', verbose_name='Đơn vị kiến thức xung đột')),
            ],
            options={
                'verbose_name': 'Nhật ký xung đột tri thức',
                'verbose_name_plural': 'Danh sách nhật ký xung đột tri thức',
                'indexes': [models.Index(fields=['group', 'status'], name='idx_conflict_group_status')],
            },
        ),
    ]
