# Generated by Django 5.2.16 on 2026-07-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0002_alter_knowledgeunit_context_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý AI'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_type',
            field=models.CharField(choices=[('chat', 'Thảo luận'), ('auto', 'Tự động học')], default='chat', max_length=10, verbose_name='Loại tải lên'),
        ),
    ]
