# Generated by Django 5.2.16 on 2026-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0002_conflictresolutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechapter',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata & Conflict Info'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('ready_to_approve', 'Ready to Approve'), ('conflict_detected', 'Conflict Detected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
