# Generated by Django 5.2.16 on 2026-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0003_document_processed_at_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='ai_model',
            field=models.CharField(default='gpt-4o', max_length=100, verbose_name='Model AI đang dùng'),
        ),
    ]
