# Generated by Django 5.2.16 on 2026-08-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0003_knowledgechapter_metadata_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgechapter',
            new_name='idx_kchapter_group_status',
            old_name='group_chat__group_i_4b8fdf_idx',
        ),
        migrations.AddField(
            model_name='knowledgechapter',
            name='suggested_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung AI biên soạn gợi ý'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='group_id',
            field=models.UUIDField(db_index=True, verbose_name='ID Nhóm chat'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='has_conflict',
            field=models.BooleanField(default=False, verbose_name='Có mâu thuẫn ngữ nghĩa'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata & Thông tin xung đột'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group_chat.knowledgechapter', verbose_name='Mục lục cha'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('ready_to_approve', 'Ready to Approve'), ('conflict_detected', 'Conflict Detected'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Trạng thái vòng đời'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Tóm tắt nội dung chính'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề chương'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Phiên bản khóa lạc quan'),
        ),
    ]
