# Generated by Django 5.2.16 on 2026-08-28 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0004_rename_group_chat__group_i_4b8fdf_idx_idx_kchapter_group_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lưu thông tin layout, mục lục gợi ý từ AI Auditor.'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('STAGING', 'Đang phân tích cấu trúc'), ('APPROVED', 'Đã duyệt & Sync'), ('FAILED', 'Lỗi/Dữ liệu rác')], default='PENDING', max_length=10, verbose_name='Trạng thái xử lý'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('staging', 'Đang phân tích / Staging'), ('ready_to_approve', 'Sẵn sàng phê duyệt'), ('conflict_detected', 'Phát hiện xung đột'), ('approved', 'Đã phê duyệt')], default='pending', max_length=20, verbose_name='Trạng thái vòng đời'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['group', 'status'], name='group_chat__group_i_754b6b_idx'),
        ),
    ]
