# Generated by Django 5.2.16 on 2026-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0004_chatgroup_ai_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={},
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('ollama', 'Ollama')], default='gemini', max_length=50, verbose_name='Provider AI'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='custom_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key riêng của nhóm'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_admin_group',
            field=models.BooleanField(default=False, help_text='Nhóm này sẽ dùng chung cấu hình gốc từ LLMService', verbose_name='Là nhóm Admin hệ thống?'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model AI đang dùng'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='plan_type',
            field=models.CharField(default='free', max_length=50, verbose_name='Gói dịch vụ'),
        ),
    ]
