# Generated by Django 5.2.16 on 2026-08-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0005_document_metadata_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='group_chat.document', verbose_name='Tài liệu gốc'),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='raw_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung thô'),
        ),
    ]
