# Generated by Django 5.2.16 on 2026-08-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0005_alter_chatgroup_options_chatgroup_ai_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='is_admin_group',
            field=models.BooleanField(default=False, verbose_name='Là nhóm Admin hệ thống?'),
        ),
    ]
