# Generated by Django 5.2.16 on 2026-08-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0006_rawdocument_document_rawdocument_raw_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdocument',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_document', to='group_chat.document', verbose_name='Tài liệu gốc'),
        ),
    ]
