# Generated by Django 5.2.16 on 2026-08-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0006_alter_chatgroup_is_admin_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Nhóm chat', 'verbose_name_plural': 'Danh sách nhóm chat'},
        ),
    ]
