# Generated by Django 5.2.16 on 2026-08-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0007_alter_chatgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Liên kết đến tin nhắn gốc nếu đây là tin nhắn reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='group_chat.message', verbose_name='Trả lời cho tin nhắn'),
        ),
    ]
