# Generated by Django 5.2.16 on 2026-09-12 11:42

import apps.group_chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0007_alter_rawdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('staging', 'Đang phân tích cấu trúc'), ('approved', 'Đã duyệt & Sync'), ('failed', 'Lỗi/Dữ liệu rác')], default='pending', max_length=20, verbose_name='Trạng thái xử lý'),
        ),
        migrations.AlterField(
            model_name='rawdocument',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[apps.group_chat.validators.validate_file_size], verbose_name='Tài liệu tải lên'),
        ),
        migrations.AlterField(
            model_name='rawdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('staging', 'Đang phân tích cấu trúc'), ('approved', 'Đã duyệt & Sync'), ('failed', 'Lỗi/Dữ liệu rác')], default='pending', max_length=20),
        ),
    ]
