# Generated by Django 5.2.16 on 2026-09-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0008_alter_document_status_alter_rawdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechapter',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
