# Generated by Django 5.2.16 on 2026-08-06 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0008_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Liên kết đến tệp tài liệu nếu tin nhắn này là file upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='group_chat.document', verbose_name='Tài liệu đính kèm'),
        ),
    ]
