# Generated by Django 5.2.16 on 2026-09-20 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0009_knowledgechapter_approved_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgechapter',
            options={'verbose_name': 'Chương tri thức', 'verbose_name_plural': 'Danh sách chương tri thức'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgechapter',
            name='idx_kchapter_group_status',
        ),
        migrations.RemoveField(
            model_name='knowledgechapter',
            name='group_id',
        ),
        migrations.AddField(
            model_name='knowledgechapter',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chapters', to='group_chat.chatgroup', verbose_name='Nhóm chat'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('staging', 'Đang phân tích / Staging'), ('ready_to_approve', 'Sẵn sàng phê duyệt'), ('conflict_detected', 'Phát hiện xung đột'), ('approved', 'Đã phê duyệt')], default='pending', max_length=30, verbose_name='Trạng thái vòng đời'),
        ),
        migrations.AlterField(
            model_name='knowledgechapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='knowledgechapter',
            table='knowledge_chapters',
        ),
    ]
