# Generated by Django 5.2.16 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0009_message_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tệp gốc'),
        ),
    ]
