# Generated by Django 5.2.16 on 2026-08-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0010_document_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='custom_api_key',
        ),
    ]
