# Generated by Django 5.2.16 on 2026-08-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0011_remove_chatgroup_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_learned',
            field=models.BooleanField(default=False, help_text='Đánh dấu tin nhắn đã được AI quét và đưa vào luồng học tập', verbose_name='Đã học tổng hợp tri thức'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi'),
        ),
    ]
