# Generated by Django 5.2.16 on 2026-08-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0012_message_is_learned_alter_message_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('has_conflict', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group_chat.knowledgechapter')),
            ],
            options={
                'verbose_name': 'Phân cấp chương tri thức',
                'verbose_name_plural': 'Phân cấp chương tri thức',
                'indexes': [models.Index(fields=['group_id', 'status'], name='group_chat__group_i_4b8fdf_idx')],
            },
        ),
    ]
