# Generated by Django 5.2.16 on 2026-08-10 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0013_knowledgechapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechapter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='knowledgechapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
