# Generated by Django 5.2.16 on 2026-08-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0014_knowledgechapter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgechapter',
            options={'verbose_name': 'Mục lục tri thức', 'verbose_name_plural': 'Mục lục tri thức'},
        ),
    ]
