# Generated by Django 5.2.13 on 2026-05-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_coach', '0003_alter_datatype_options_datatype_ai_model_preference_and_more'),
        ('app_miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Thuật ngữ/Logic')),
                ('category', models.CharField(choices=[('LOGIC', 'Logic tính toán'), ('TERM', 'Định nghĩa/Nghiệp vụ')], default='TERM', max_length=50, verbose_name='Phân loại')),
                ('content', models.TextField(verbose_name='Mô tả chi tiết cho AI')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ AI tóm tắt'), ('AI_READY', 'AI đã soạn xong'), ('EDITED', 'Anh Vũ đã sửa'), ('FINAL', 'Đã chốt (Nạp vào RAG)')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('origin_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata gốc từ Miner')),
                ('backup_hash', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_coach.datatype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='app_miner.datasource')),
                ('sheet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_draft', to='app_miner.dataentry')),
            ],
            options={
                'verbose_name': '1. Bản thảo tri thức',
                'verbose_name_plural': '1. Bản thảo tri thức',
            },
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi AI')),
                ('admin_answer', models.TextField(blank=True, null=True, verbose_name='Câu trả lời của anh Vũ')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Đã nạp tri thức')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_miner.datasource', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': '2. Nhật ký AI tự học',
                'verbose_name_plural': '2. Nhật ký AI tự học',
            },
        ),
    ]
