# Generated by Django 6.0.7 on 2026-07-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_alter_profile_options'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(to='subscriptions.feature', verbose_name='Tính năng bao gồm'),
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Công ty')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='Gói dịch vụ hiện tại')),
            ],
            options={
                'verbose_name': 'Đăng ký dịch vụ công ty',
            },
        ),
    ]
