# Generated by Django 6.0.7 on 2026-07-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_alter_profile_options'),
        ('subscriptions', '0002_alter_subscriptionplan_features_companysubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Đăng ký dịch vụ công ty', 'verbose_name_plural': 'Đăng ký dịch vụ công ty'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Tính năng', 'verbose_name_plural': 'Các tính năng'},
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(default=0, help_text='Mô tả ngắn gọn về gói dịch vụ.', verbose_name='Mô tả chi tiết'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Số tiền khách hàng phải trả hàng tháng.', max_digits=12, verbose_name='Giá tiền (VNĐ/tháng)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Mã gói (Slug)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã định danh (Slug)'),
        ),
    ]
