# Generated by Django 5.2.13 on 2026-05-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gợi nhớ')),
                ('module_code', models.CharField(db_index=True, max_length=50, verbose_name='Mã Module')),
                ('function_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã Chức năng')),
                ('is_default', models.BooleanField(default=False, verbose_name='Cấu hình mặc định')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
                ('confidence_threshold', models.IntegerField(default=85, verbose_name='Ngưỡng tự tin (%)')),
                ('temperature', models.FloatField(default=0.2, verbose_name='Độ sáng tạo (0.1 - 0.5)')),
                ('provider_strategy', models.CharField(choices=[('AUTO', 'Tự động (Dựa trên Token Count)'), ('OLLAMA', 'Ép dùng Ollama (Local)'), ('GROQ', 'Ưu tiên Groq (Cloud)'), ('GEMINI', 'Ưu tiên Gemini (Cloud)')], default='AUTO', max_length=20, verbose_name='Chiến lược chọn AI')),
                ('model_name', models.CharField(blank=True, help_text='Ví dụ: qwen2.5:7b hoặc llama-3.1-70b', max_length=100, verbose_name='Model cụ thể')),
                ('max_token_threshold', models.IntegerField(default=6000, verbose_name='Ngưỡng chuyển đổi Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Prompt AI',
                'verbose_name_plural': 'Kho Prompt AI',
                'ordering': ['module_code', 'function_code'],
                'unique_together': {('module_code', 'function_code')},
            },
        ),
    ]
