# Generated by Django 5.2.13 on 2026-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aipromptconfig',
            options={'verbose_name': 'Cấu hình Prompt AI', 'verbose_name_plural': 'Kho Prompt AI'},
        ),
        migrations.RemoveField(
            model_name='aipromptconfig',
            name='confidence_threshold',
        ),
        migrations.AddField(
            model_name='aipromptconfig',
            name='num_ctx',
            field=models.IntegerField(default=8192, verbose_name='Context Window (Ollama)'),
        ),
        migrations.AddField(
            model_name='aipromptconfig',
            name='num_gpu_layers',
            field=models.IntegerField(default=50, help_text='Số layer đẩy lên GPU, 0 là chạy CPU hoàn toàn', verbose_name='GPU Layers (Ollama)'),
        ),
        migrations.AlterField(
            model_name='aipromptconfig',
            name='model_name',
            field=models.CharField(blank=True, help_text='Ví dụ: qwen2.5:7b', max_length=100, verbose_name='Model cụ thể'),
        ),
    ]
