# Generated by Django 5.2.13 on 2026-04-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excel_miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên quy trình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả tổng quan')),
                ('steps', models.JSONField(help_text='Lưu dưới dạng danh sách các bước', verbose_name='Các bước thực hiện')),
                ('logic_rules', models.TextField(verbose_name='Quy tắc logic (Công thức)')),
            ],
            options={
                'verbose_name': 'Quy trình',
                'verbose_name_plural': 'Quy trình nghiệp vụ',
            },
        ),
        migrations.CreateModel(
            name='IntentRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=100, unique=True, verbose_name='Mã ý định')),
                ('display_name', models.CharField(max_length=255, null=True, verbose_name='Tên ý định (Dễ hiểu)')),
                ('keywords', models.TextField(help_text='Phân cách bằng dấu phẩy', verbose_name='Từ khóa nhận diện')),
                ('target_app', models.CharField(max_length=50, verbose_name='App xử lý')),
                ('hit_count', models.IntegerField(default=0, verbose_name='Số lần sử dụng')),
            ],
            options={
                'verbose_name': 'Định tuyến ý định',
                'verbose_name_plural': 'Bộ định tuyến ý định (Router)',
            },
        ),
        migrations.CreateModel(
            name='BusinessTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True, verbose_name='Thuật ngữ/Khái niệm')),
                ('definition', models.TextField(verbose_name='Định nghĩa nghiệp vụ')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Ngữ cảnh sử dụng')),
                ('is_common', models.BooleanField(default=True, verbose_name='Thuật ngữ phổ biến')),
                ('source_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_miner.datafield')),
            ],
            options={
                'verbose_name': 'Thuật ngữ',
                'verbose_name_plural': 'Từ điển nghiệp vụ',
            },
        ),
    ]
