# Generated by Django 5.2.13 on 2026-05-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excel_miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhiệm vụ')),
                ('task_type', models.CharField(choices=[('USER_GUIDE', 'Viết hướng dẫn sử dụng'), ('GEN_CODE', 'Viết Code Logic'), ('UI_SCRIPT', 'Kịch bản giao diện')], max_length=50, verbose_name='Loại nhiệm vụ')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
                ('template_content', models.TextField(verbose_name='Template (Dùng {{context}})')),
            ],
            options={
                'verbose_name': 'Mẫu Prompt AI',
                'verbose_name_plural': '5. Cấu hình Prompt AI',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên quy trình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả quy trình (Markdown)')),
                ('steps', models.JSONField(blank=True, null=True, verbose_name='Danh sách bước (JSON)')),
                ('logic_rules', models.TextField(blank=True, null=True, verbose_name='Công thức / Logic tổng quát')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quy trình nghiệp vụ',
                'verbose_name_plural': '2. Quản lý quy trình (Chính thức)',
            },
        ),
        migrations.CreateModel(
            name='BusinessTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True, verbose_name='Thuật ngữ')),
                ('definition', models.TextField(verbose_name='Định nghĩa nghiệp vụ')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Ngữ cảnh sử dụng')),
                ('is_common', models.BooleanField(default=True, verbose_name='Thuật ngữ phổ biến')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thuật ngữ chính thức',
                'verbose_name_plural': '1. Từ điển nghiệp vụ (Đã duyệt)',
            },
        ),
        migrations.CreateModel(
            name='SystemGuide',
            fields=[
            ],
            options={
                'verbose_name': '📖 HƯỚNG DẪN VẬN HÀNH',
                'verbose_name_plural': '📖 HƯỚNG DẪN VẬN HÀNH',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_knowledge.businessprocess',),
        ),
        migrations.CreateModel(
            name='KnowledgeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROCESS', 'Quy trình'), ('TERM', 'Thuật ngữ'), ('LOGIC', 'Quy tắc Logic')], default='PROCESS', max_length=20, verbose_name='Loại bản thảo')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề/Thuật ngữ')),
                ('content', models.TextField(verbose_name='Nội dung (Markdown/JSON)')),
                ('origin_metadata', models.JSONField(blank=True, null=True, verbose_name='Nguồn gốc dữ liệu')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('AI_PROCESSED', 'AI đã viết'), ('APPROVED', 'Đã duyệt nạp')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='excel_miner.excelproject')),
            ],
            options={
                'verbose_name': 'Bản thảo tri thức',
                'verbose_name_plural': '3. Sàng lọc & Soạn thảo (Draft Area)',
            },
        ),
        migrations.CreateModel(
            name='BusinessLogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255, verbose_name='Tên công thức')),
                ('formula', models.TextField(verbose_name='Công thức (Python Style)')),
                ('variables', models.JSONField(help_text="Ví dụ: ['weight', 'purity']", verbose_name='Biến số')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Giải thích')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic_rules', to='ai_knowledge.knowledgedraft')),
            ],
            options={
                'verbose_name': 'Quy tắc Logic',
                'verbose_name_plural': '4. Quy tắc Logic bóc tách',
            },
        ),
    ]
