# Generated by Django 5.2.13 on 2026-04-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0001_initial'),
        ('excel_miner', '0004_alter_datafield_options_alter_datafield_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'verbose_name': 'Quy trình nghiệp vụ', 'verbose_name_plural': '3. Quản lý quy trình (Logic)'},
        ),
        migrations.AlterModelOptions(
            name='businessterm',
            options={'verbose_name': 'Thuật ngữ chính thức', 'verbose_name_plural': '1. Từ điển nghiệp vụ (Đã duyệt)'},
        ),
        migrations.AlterModelOptions(
            name='intentrouter',
            options={'verbose_name': 'Định tuyến câu hỏi', 'verbose_name_plural': '4. Bộ định tuyến AI (Router)'},
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='description',
            field=models.TextField(blank=True, help_text='Viết dạng Markdown. Ví dụ: Các bước thu mua vàng cũ.', null=True, verbose_name='Mô tả quy trình'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='logic_rules',
            field=models.TextField(help_text='Ví dụ: Giá thu mua = Giá thế giới * Tỷ giá + Tiền công.', verbose_name='Công thức / Quy tắc logic'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên quy trình nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='steps',
            field=models.JSONField(help_text="Cấu trúc: [{'step': 1, 'action': 'Kiểm tra tuổi vàng'}, ...]", verbose_name='Danh sách các bước (JSON)'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='context',
            field=models.TextField(blank=True, help_text='Dùng trong trường hợp nào? (Ví dụ: Chỉ áp dụng cho khách lẻ)', null=True, verbose_name='Ngữ cảnh sử dụng'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='definition',
            field=models.TextField(help_text='Giải thích chi tiết ý nghĩa để AI hiểu và tư vấn.', verbose_name='Định nghĩa nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='is_common',
            field=models.BooleanField(default=True, help_text='Nếu tích chọn, AI sẽ ưu tiên sử dụng thuật ngữ này cho mọi dự án.', verbose_name='Thuật ngữ phổ biến'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='source_field',
            field=models.ForeignKey(blank=True, help_text='Liên kết ngược lại ô Excel để đối soát dữ liệu khi cần.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_miner.datafield', verbose_name='Nguồn Excel gốc'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='term',
            field=models.CharField(help_text='Ví dụ: Vàng 610, Tiền công thợ, Thu đổi cũ mới.', max_length=255, unique=True, verbose_name='Thuật ngữ'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='display_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên ý định dễ hiểu'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='hit_count',
            field=models.IntegerField(default=0, verbose_name='Số lần khách hỏi'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='intent_name',
            field=models.CharField(help_text='Ví dụ: TRA_CUU_GIA_VANG, DOI_TIEN_CONG.', max_length=100, unique=True, verbose_name='Mã ý định (Intent Code)'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='keywords',
            field=models.TextField(help_text="Các từ khóa cách nhau bằng dấu phẩy để AI 'bắt' được ý định khách hàng.", verbose_name='Từ khóa nhận diện'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='target_app',
            field=models.CharField(help_text='Tên của Module Python hoặc API sẽ xử lý ý định này.', max_length=50, verbose_name='App xử lý'),
        ),
        migrations.CreateModel(
            name='BusinessTermDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500, verbose_name='Thuật ngữ thô')),
                ('sheet_name', models.CharField(max_length=255, verbose_name='Tên Sheet gốc')),
                ('context', models.TextField(help_text='Cột nào, dòng nào, lân cận có gì.', verbose_name='Vị trí trong Excel')),
                ('ui_type', models.CharField(blank=True, help_text='AI xác định đây là Nút bấm, Tiêu đề hay Ô nhập liệu.', max_length=100, null=True, verbose_name='Phân loại UI')),
                ('definition', models.TextField(blank=True, help_text='Kết quả AI trả về sau khi đọc ngữ cảnh Excel.', null=True, verbose_name='AI Dự đoán định nghĩa')),
                ('suggested_code', models.CharField(blank=True, help_text='Mã chuẩn hóa để lập trình phần mềm (ví dụ: GOLD_RETAIL_PRICE).', max_length=100, null=True, verbose_name='Mã gợi ý (Code)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt (Mới quét)'), ('SENT', 'Đang đợi AI xử lý'), ('DONE', 'Đã kiểm duyệt & Đẩy vào Từ điển')], default='PENDING', help_text='Luồng: PENDING -> SENT -> DONE', max_length=20, verbose_name='Trạng thái xử lý')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_miner.excelproject', verbose_name='Dự án Excel')),
            ],
            options={
                'verbose_name': 'Bản nháp tri thức',
                'verbose_name_plural': '2. Sàng lọc thuật ngữ (Draft)',
                'unique_together': {('project', 'term', 'sheet_name')},
            },
        ),
    ]
