# Generated by Django 5.2.13 on 2026-05-06 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nghiệp vụ')),
                ('slug', models.SlugField(help_text='Dùng để khớp với file JSON và Router', unique=True, verbose_name='Mã định danh (Slug)')),
                ('task_type', models.CharField(choices=[('EXTRACT', 'Bóc tách dữ liệu (Excel/PDF/Img)'), ('LOGIC_GEN', 'Soạn thảo quy trình vận hành'), ('CHAT_GUIDE', 'Định hướng hội thoại Chatbot')], default='EXTRACT', max_length=50, verbose_name='Loại nhiệm vụ')),
                ('system_prompt', models.TextField(help_text='Vai trò và luật chơi của AI', verbose_name='System Instruction')),
                ('user_prompt_template', models.TextField(help_text='Dùng {{data}} hoặc {{context}} để truyền nội dung', verbose_name='User Prompt Template')),
                ('learning_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú tri thức (AI tự đúc kết)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('priority', models.IntegerField(default=0, verbose_name='Độ ưu tiên')),
            ],
            options={
                'verbose_name': 'Nghiệp vụ điều hướng',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.TextField(verbose_name='AI bóc tách sai')),
                ('corrected_value', models.TextField(verbose_name='Chủ tiệm sửa lại đúng')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Lý do thay đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhật ký sửa lỗi (Học tăng cường)',
            },
        ),
        migrations.DeleteModel(
            name='AIPromptTemplate',
        ),
        migrations.RemoveField(
            model_name='businesslogicrule',
            name='draft',
        ),
        migrations.DeleteModel(
            name='SystemGuide',
        ),
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'verbose_name': 'Quy trình chính thức'},
        ),
        migrations.AlterModelOptions(
            name='businessterm',
            options={'verbose_name': 'Từ điển nghiệp vụ'},
        ),
        migrations.AlterModelOptions(
            name='knowledgedraft',
            options={'verbose_name': 'Bản thảo tri thức'},
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='businessterm',
            name='context',
        ),
        migrations.RemoveField(
            model_name='businessterm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businessterm',
            name='is_common',
        ),
        migrations.RemoveField(
            model_name='knowledgedraft',
            name='category',
        ),
        migrations.RemoveField(
            model_name='knowledgedraft',
            name='origin_metadata',
        ),
        migrations.RemoveField(
            model_name='knowledgedraft',
            name='project',
        ),
        migrations.RemoveField(
            model_name='knowledgedraft',
            name='title',
        ),
        migrations.RemoveField(
            model_name='knowledgedraft',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Cho phép Chatbot sử dụng'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessterm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='conflict_details',
            field=models.TextField(blank=True, help_text='AI tự liệt kê các điểm khác biệt so với tri thức cũ', null=True, verbose_name='Chi tiết mâu thuẫn'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='project_id',
            field=models.IntegerField(default=0, verbose_name='ID dự án gốc'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='logic_rules',
            field=models.JSONField(blank=True, null=True, verbose_name='Công thức máy tính (JSON)'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên quy trình/công thức'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='content',
            field=models.TextField(verbose_name='Nội dung AI soạn thảo'),
        ),
        migrations.AlterField(
            model_name='knowledgedraft',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('CONFLICT', 'Phát hiện mâu thuẫn'), ('APPROVED', 'Đã thống nhất')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_knowledge.businesstask'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='ai_knowledge.businesstask'),
        ),
        migrations.AddField(
            model_name='correctionledger',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_knowledge.knowledgedraft'),
        ),
        migrations.AddField(
            model_name='correctionledger',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_knowledge.businesstask'),
        ),
        migrations.DeleteModel(
            name='BusinessLogicRule',
        ),
    ]
