# Generated by Django 5.2.13 on 2026-04-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0002_alter_businessprocess_options_and_more'),
        ('excel_miner', '0004_alter_datafield_options_alter_datafield_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'verbose_name': 'Quy trình nghiệp vụ', 'verbose_name_plural': '2. Quản lý quy trình (Chính thức)'},
        ),
        migrations.AlterModelOptions(
            name='businesstermdraft',
            options={'verbose_name': 'Bản nháp thuật ngữ', 'verbose_name_plural': '4. Sàng lọc thuật ngữ (Draft)'},
        ),
        migrations.AlterModelOptions(
            name='intentrouter',
            options={'verbose_name': 'Định tuyến AI', 'verbose_name_plural': '5. Bộ định tuyến AI (Router)'},
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả quy trình (Markdown)'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='logic_rules',
            field=models.TextField(blank=True, null=True, verbose_name='Công thức / Logic'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên quy trình'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='steps',
            field=models.JSONField(blank=True, null=True, verbose_name='Danh sách bước (JSON)'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Ngữ cảnh sử dụng'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='definition',
            field=models.TextField(verbose_name='Định nghĩa nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='is_common',
            field=models.BooleanField(default=True, verbose_name='Thuật ngữ phổ biến'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='source_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_miner.datafield'),
        ),
        migrations.AlterField(
            model_name='businessterm',
            name='term',
            field=models.CharField(max_length=255, unique=True, verbose_name='Thuật ngữ'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='context',
            field=models.TextField(verbose_name='Vị trí trong Excel'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='definition',
            field=models.TextField(blank=True, null=True, verbose_name='AI Dự đoán định nghĩa'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_miner.excelproject'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('SENT', 'Đang đợi AI'), ('DONE', 'Đã duyệt')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='suggested_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Code'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='ui_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại UI'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='display_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên ý định'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='hit_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt hỏi'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='intent_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mã ý định'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='keywords',
            field=models.TextField(verbose_name='Từ khóa nhận diện'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='target_app',
            field=models.CharField(max_length=50, verbose_name='App xử lý'),
        ),
        migrations.CreateModel(
            name='BusinessProcessDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255, verbose_name='Thuộc Sheet')),
                ('process_name', models.CharField(max_length=255, verbose_name='Tên quy trình dự kiến')),
                ('draft_content', models.TextField(verbose_name='Nội dung bản thảo (Sửa tại đây)')),
                ('logic_mapping', models.JSONField(blank=True, null=True, verbose_name='Bản đồ tọa độ gốc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ sửa (AI mới soạn)'), ('REVISED', 'Đã chỉnh sửa'), ('APPROVED', 'Đã duyệt nạp chính thức')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_miner.excelproject')),
            ],
            options={
                'verbose_name': 'Bản thảo quy trình',
                'verbose_name_plural': '3. Soạn thảo quy trình (Draft)',
            },
        ),
    ]
