# Generated by Django 5.2.13 on 2026-05-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0002_businesstask_correctionledger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'verbose_name': 'Quy trình chính thức', 'verbose_name_plural': 'Quy trình chính thức'},
        ),
        migrations.AlterModelOptions(
            name='businesstask',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Nghiệp vụ điều hướng', 'verbose_name_plural': 'Nghiệp vụ điều hướng'},
        ),
        migrations.AlterModelOptions(
            name='businessterm',
            options={'verbose_name': 'Từ điển nghiệp vụ', 'verbose_name_plural': 'Từ điển nghiệp vụ'},
        ),
        migrations.AlterModelOptions(
            name='correctionledger',
            options={'verbose_name': 'Nhật ký sửa lỗi (Học tăng cường)', 'verbose_name_plural': 'Nhật ký sửa lỗi (Học tăng cường)'},
        ),
        migrations.AlterModelOptions(
            name='knowledgedraft',
            options={'verbose_name': 'Bản thảo tri thức', 'verbose_name_plural': 'Bản thảo tri thức'},
        ),
    ]
