# Generated by Django 5.2.13 on 2026-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0003_alter_businessprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedraft',
            name='category',
            field=models.CharField(default='TERM', max_length=50, verbose_name='Phân loại'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='origin_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu thô'),
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='term',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thuật ngữ/Tiêu đề'),
        ),
    ]
