# Generated by Django 5.2.13 on 2026-05-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0003_alter_businessprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstermdraft',
            name='process_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_terms', to='ai_knowledge.businessprocessdraft'),
        ),
        migrations.CreateModel(
            name='BusinessLogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255, verbose_name='Tên công thức')),
                ('formula', models.TextField(verbose_name='Công thức (Excel/Python style)')),
                ('variables', models.JSONField(help_text='Ví dụ: {weight, purity, gold_price}', verbose_name='Các biến số cần nạp')),
                ('process_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_rules', to='ai_knowledge.businessprocessdraft')),
            ],
        ),
    ]
