# Generated by Django 5.2.13 on 2026-05-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0004_knowledgedraft_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstask',
            name='knowledge_base',
            field=models.TextField(blank=True, verbose_name='Kho tri thức đúc kết'),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung đoạn')),
                ('chunk_type', models.CharField(choices=[('SHEET', 'Bảng tính'), ('PARA', 'Đoạn văn'), ('IMAGE_ZONE', 'Vùng ảnh')], default='SHEET', max_length=20, verbose_name='Loại chunk')),
                ('metadata', models.JSONField(verbose_name='Thông tin gốc (Vị trí sheet/trang)')),
                ('vector_id', models.CharField(blank=True, max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_knowledge.businesstask')),
            ],
            options={
                'verbose_name': 'Mảnh ghép tri thức',
                'verbose_name_plural': 'Mảnh ghép tri thức',
            },
        ),
        migrations.AddField(
            model_name='knowledgedraft',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, to='ai_knowledge.knowledgechunk', verbose_name='Nguồn dữ liệu bóc tách'),
        ),
    ]
