# Generated by Django 5.2.13 on 2026-05-01 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_knowledge', '0004_businesstermdraft_process_draft_businesslogicrule'),
        ('excel_miner', '0005_datafield_functional_group_datafield_is_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslogicrule',
            options={'verbose_name': 'Quy tắc Logic', 'verbose_name_plural': '6. Quy tắc Logic (Bóc tách từ AI)'},
        ),
        migrations.AddField(
            model_name='businesslogicrule',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Giải thích bình dân'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprocessdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesslogicrule',
            name='process_draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_rules_draft', to='ai_knowledge.businessprocessdraft'),
        ),
        migrations.AlterField(
            model_name='businesslogicrule',
            name='variables',
            field=models.JSONField(help_text="Ví dụ: ['weight', 'purity']", verbose_name='Các biến số cần nạp'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='logic_rules',
            field=models.TextField(blank=True, null=True, verbose_name='Công thức / Logic tổng quát'),
        ),
        migrations.AlterField(
            model_name='businessprocessdraft',
            name='draft_content',
            field=models.TextField(verbose_name='Nội dung bản thảo (Markdown)'),
        ),
        migrations.AlterField(
            model_name='businessprocessdraft',
            name='logic_mapping',
            field=models.JSONField(blank=True, null=True, verbose_name='Bản đồ ngữ cảnh UI'),
        ),
        migrations.AlterField(
            model_name='businessprocessdraft',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ gởi AI'), ('REVISED', 'Đã chỉnh sửa'), ('APPROVED', 'Đã duyệt nạp')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='businesstermdraft',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Vị trí/Ngữ cảnh trong Excel'),
        ),
        migrations.AlterField(
            model_name='intentrouter',
            name='keywords',
            field=models.TextField(verbose_name='Từ khóa nhận diện (Phân cách bằng dấu phẩy)'),
        ),
        migrations.AlterUniqueTogether(
            name='businessprocessdraft',
            unique_together={('project', 'sheet_name')},
        ),
    ]
